#!/bin/bash

#
# Web project prepare
# By BratAnon / Anon
#
# Usage : ./web_project_prepare foo.dev
#

PROJECT_NAME=$1

MYSQL_USER=root
MYSQL_PASS=password

WEB_ROOT=$HOME/www
PROJECT_WEB_ROOT=$WEB_ROOT/$PROJECT_NAME/web

APACHE_VHOST_PATH=/etc/httpd/conf/vhosts

HOST_FILE=/etc/hosts
IP_ADDRESS=127.0.0.1

# Is drush installed?
if ! hash drush 2>/dev/null; then
  echo "I require drush but it's not installed.  Aborting.";
  exit 1;
fi

if [ -z $PROJECT_NAME ]; then
  echo "I need a project name to continue."
  exit
fi

echo "I need sudo permissions to play around with the vhost and host file.";
sudo -v
echo

# Create project web root.
if [ ! -d $PROJECT_WEB_ROOT ]; then
  echo "Creating project directory. ($PROJECT_WEB_ROOT)"
  mkdir -p $PROJECT_WEB_ROOT
else
  echo "Project directory already exists. ($PROJECT_WEB_ROOT)"
fi

# Download Drupal?
read -p "Download Drupal? [N/y] "
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
  echo "Will download Drupal."
  cd $PROJECT_WEB_ROOT
  cd ..
  echo "Downloading drupal, please wait."
  drush dl drupal --drupal-project-rename=web -y
  echo "Drupal were downloaded to '$PROJECT_WEB_ROOT'"
fi

# If the vhost.template file does not exists, download it.
if [ ! -f $APACHE_VHOST_PATH/vhost.template ]; then
  echo "Downloading vhost template."
  sudo wget -qP $APACHE_VHOST_PATH https://raw.githubusercontent.com/bratanon/web_project_prepare/master/vhost.template
fi

# Create new vhost file
echo "Creating vhost file."
sudo -- sh -c "sed -e 's;{{PROJECT_NAME}};$PROJECT_NAME;g' -e 's;{{PROJECT_WEB_ROOT}};$PROJECT_WEB_ROOT;g' $APACHE_VHOST_PATH/vhost.template > $APACHE_VHOST_PATH/$PROJECT_NAME.conf"
echo "Vhost file created '$APACHE_VHOST_PATH/$PROJECT_NAME.conf'"

echo "Restarting apache."
sudo systemctl restart httpd.service

#Add an instace to the HOSTS file
sudo -- sh -c "echo -e '$IP_ADDRESS\t$PROJECT_NAME' >> $HOST_FILE"
echo "'$IP_ADDRESS $PROJECT_NAME' added to the host file."

# Create mysql databas?
read -p "Create mysql databas? [N/y] "
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
  echo "Creating mysql database."
  mysql -u$MYSQL_USER -p$MYSQL_PASS -e "CREATE DATABASE \`$PROJECT_NAME\`"
fi